version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 2
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 2
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch', 'version-update:semver-minor']
    groups:
      npm-dependencies:
        patterns:
          - "*"
