name: Sync dev with main

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Merge main -> dev
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch origin dev:dev
          git checkout dev
          git merge origin/main
          git push origin dev
